### ISSUE TITLE
Error Starting Strongbox

### ISSUE THREAD

**Issue by privacytoolsIO** [benhj/Strongbox#11]
Process:               Strongbox [2357]
Path:                  /Applications/Strongbox.app/Contents/MacOS/Strongbox
Identifier:            benhj.Strongbox
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Strongbox [2357]
User ID:               501

Date/Time:             2016-06-02 23:19:24.853 +0200
OS Version:            Mac OS X 10.11.5 (15F34)
Report Version:        11
Anonymous UUID:        055896BD-2477-42B6-CDCF-4AFEB9591398

Sleep/Wake UUID:       B8C564C6-D849-426B-B460-C041BA2FE1C9

Time Awake Since Boot: 81000 seconds
Time Since Wake:       39000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/boost/lib/libboost_system.dylib
  Referenced from: /Applications/Strongbox.app/Contents/MacOS/Strongbox
  Reason: image not found

Binary Images:
    0x7fff6cefe000 -     0x7fff6cf3525f  dyld (360.22) <A468D85E-D8D6-3461-8C99-49D3B9ACFC63> /usr/lib/dyld

Model: MacBookPro10,1, BootROM MBP101.00EE.B0A, 4 processors, Intel Core i7, 2,7 GHz, 16 GB, SMC 2.3f36
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Graphics: NVIDIA GeForce GT 650M, NVIDIA GeForce GT 650M, PCIe, 1024 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xEF), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
Bluetooth: Version 4.4.5f3 17904, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM768E, 751,28 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 23.4

**Comment by benhj** [comment]
Thanks for reporting this issue. Looks like some of the boost library dependencies aren't being properly shipped. I'll have a fix for this within the next few days hopefully.

**Comment by benhj** [comment]
Hello, could you try the latest version, 0.02B, and let me know if you have any more issues! Thanks.

**Comment by privacytoolsIO** [comment]
Thanks, I can start the app now.

**Comment by benhj** [comment]
Awesome! Closing issue. Thanks again!
